title: Seohyun Dev Blog
email: shp7408@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This space is where I organize and summarize the things I have studied related to development.
author: Seohyun Park, Aileen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shp7408.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github_username:  shp7408
linkedin_username: seohyun-park-a071ba215

# Google Analytics
google_analytics: G-562FQESFKN

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
# theme: jekyll-theme-clean-blog
