title: Seohyun Park's blog
email: shp7408@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This space is where I organize and summarize the things I have studied related to development.
author: Seohyun Park, Aileen
baseurl: 
url: "https://shp7408.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github_username:  shp7408
linkedin_username: seohyun-park-a071ba215

# Google Analytics
google_analytics: G-562FQESFKN

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
theme: jekyll-theme-clean-blog

# # Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely edit after that. If you find
# # yourself editing this file very often, consider using Jekyll's data files
# # feature for the data you need to update frequently.
# #
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# #
# # If you need help with YAML syntax, here are some quick references for you:
# # https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# # https://learnxinyminutes.com/docs/yaml/
# #
# # Site settings
# # These are used to personalize your new site. If you look in the HTML files,
# # you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# # You can create any custom variable you would like, and they will be accessible
# # in the templates via {{ site.myvariable }}.

# title: Blog
# email: shp7408@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   This space is where I organize and summarize the things I have studied related to development.
# author: Seohyun Park, Aileen
# social:
#   github: shp7408
#   linkedin: seohyun-park-a071ba215
# logo: /img/1.svg
# img_prefix:  # cloud image prefix
# rss: /feed.xml

# baseurl:  # the subpath of your site, e.g. /blog
# url: "https://shp7408.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  shp7408

# # Build settings
# theme: jekyll-theme-clean-blog
# remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
# plugins:
#   - jekyll-feed

# theme_setting:
#   slides_count: 5
# #   # The ← back URL on the top of your post page. Default is your site's home page.
#   blog_page: blog.md
# #   # The URL on your name on the bottom of your post and page. Default is your site's home page.
#   about_page: about.md
# #   #  The URL of the menu icon(which has three black lines). Will be shown on the slides/book/chapter layouts It won't be shown if blank.
#   archive_page: archive.md
#   nav_pages:
#     - title: Home
#       url: https://shp7408.github.io
#     - title: Blog
#       url: https://shp7408.github.io/blog
#     - title: About
#       url: https://shp7408.github.io/about
#     - title: Archive
#       url: https://shp7408.github.io/archive

#   code: true
#   math: true
#   mermaid: true

#   lang:
#     category_all: All
#     blog_title: Blog

# head_code:
#   <!-- Google tag (gtag.js) -->
#   <script async src="https://www.googletagmanager.com/gtag/js?id=G-562FQESFKN"></script>
#   <script>
#     window.dataLayer = window.dataLayer || [];
#     function gtag(){dataLayer.push(arguments);}
#     gtag('js', new Date());

#     gtag('config', 'G-562FQESFKN');
#   </script>

# #     comment:
# #       user: "Nickname"
# #       email: "Email"
# #       url: "Website link"
# #       message: "Leave a comment..."
# #       reply: "Reply"
# #       reply_title: "Reply to %{name}"
# #       edit: "Edit"
# #       delete: "Delete"
# #       delete_confirm: "Are you sure to delete this comment?"
# #       submit: "Submit"
# #       submitting: "Submitting..."
# #       submitted: "Submitted"
# #       failed: "Failed to submit"


# # Exclude from processing.
# # The following items will not be processed, by default.
# # Any item listed under the `exclude:` key here will be automatically added to
# # the internal "default list".
# #
# # Excluded items can be processed by explicitly listing the directories or
# # their entries' file path in the `include:` list.
# #
# # exclude:
# #   - .sass-cache/
# #   - .jekyll-cache/
# #   - gemfiles/
# #   - Gemfile
# #   - Gemfile.lock
# #   - node_modules/
# #   - vendor/bundle/
# #   - vendor/cache/
# #   - vendor/gems/
# #   - vendor/ruby/
